name: 'tasman_dbt_utils'
version: '0.0.1'

require-dbt-version: [">=1.6.0", "<2.0.0"]

config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
model-paths: ["models"]
test-paths: ["tests"]
log-path: "logs"
