name: 'tasman_dbt_utils_integration_tests'
version: '1.0'

config-version: 2

profile: 'tasman_integration_tests'

seed-paths: ["data"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
log-path: "logs"